# Machine Learning model for Stock market data
## The goal is to to predict INFY,TCS prices for tomorrow. 

In [69]:
import pandas as pd
import numpy as np
from pandas import datetime

import seaborn as sns

import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression

In [51]:
tcs_data = pd.read_csv('tcs_stock_data.csv')
tcs_data.head(5)

Date Symbol Series  Prev Close    Open     High      Low     Last  \
0  2015-01-01    TCS     EQ     2558.25  2567.0  2567.00  2541.00  2550.00   
1  2015-01-02    TCS     EQ     2545.55  2551.0  2590.95  2550.60  2588.40   
2  2015-01-05    TCS     EQ     2579.45  2581.0  2599.90  2524.65  2538.10   
3  2015-01-06    TCS     EQ     2540.25  2529.1  2529.10  2440.00  2450.05   
4  2015-01-07    TCS     EQ     2446.60  2470.0  2479.15  2407.45  2426.90   

     Close     VWAP   Volume      Turnover  Trades  Deliverable Volume  \
0  2545.55  2548.51   183415  4.674345e+13    8002               52870   
1  2579.45  2568.19   462870  1.188740e+14   27585              309350   
2  2540.25  2563.94   877121  2.248886e+14   43234              456728   
3  2446.60  2466.90  1211892  2.989615e+14   84503              714306   
4  2417.70  2433.96  1318166  3.208362e+14  101741              886368   

   %Deliverble  
0       0.2883  
1       0.6683  
2       0.5207  
3       0.5894  
4       0.6724

In [48]:
tcs_data.set_index('Date')
tcs_data.head(5)

Date Symbol Series  Prev Close    Open     High      Low     Last  \
0  2015-01-01    TCS     EQ     2558.25  2567.0  2567.00  2541.00  2550.00   
1  2015-01-02    TCS     EQ     2545.55  2551.0  2590.95  2550.60  2588.40   
2  2015-01-05    TCS     EQ     2579.45  2581.0  2599.90  2524.65  2538.10   
3  2015-01-06    TCS     EQ     2540.25  2529.1  2529.10  2440.00  2450.05   
4  2015-01-07    TCS     EQ     2446.60  2470.0  2479.15  2407.45  2426.90   

     Close     VWAP   Volume      Turnover  Trades  Deliverable Volume  \
0  2545.55  2548.51   183415  4.674345e+13    8002               52870   
1  2579.45  2568.19   462870  1.188740e+14   27585              309350   
2  2540.25  2563.94   877121  2.248886e+14   43234              456728   
3  2446.60  2466.90  1211892  2.989615e+14   84503              714306   
4  2417.70  2433.96  1318166  3.208362e+14  101741              886368   

   %Deliverble  
0       0.2883  
1       0.6683  
2       0.5207  
3       0.5894  
4       0.6724

In [11]:
tcs_data.head(10)

Date Symbol Series  Prev Close    Open     High      Low     Last  \
0 2015-01-01    TCS     EQ     2558.25  2567.0  2567.00  2541.00  2550.00   
1 2015-01-02    TCS     EQ     2545.55  2551.0  2590.95  2550.60  2588.40   
2 2015-01-03    TCS     EQ     2545.55  2551.0  2590.95  2550.60  2588.40   
3 2015-01-04    TCS     EQ     2545.55  2551.0  2590.95  2550.60  2588.40   
4 2015-01-05    TCS     EQ     2579.45  2581.0  2599.90  2524.65  2538.10   
5 2015-01-06    TCS     EQ     2540.25  2529.1  2529.10  2440.00  2450.05   
6 2015-01-07    TCS     EQ     2446.60  2470.0  2479.15  2407.45  2426.90   
7 2015-01-08    TCS     EQ     2417.70  2442.4  2449.00  2420.55  2446.00   
8 2015-01-09    TCS     EQ     2443.80  2455.0  2519.90  2450.00  2510.00   
9 2015-01-10    TCS     EQ     2443.80  2455.0  2519.90  2450.00  2510.00   

     Close     VWAP   Volume      Turnover  Trades  Deliverable Volume  \
0  2545.55  2548.51   183415  4.674345e+13    8002               52870   
1  2579.45  2568.19   462870  1.188740e+14   27585              309350   
2  2579.45  2568.19   462870  1.188740e+14   27585              309350   
3  2579.45  2568.19   462870  1.188740e+14   27585              309350   
4  2540.25  2563.94   877121  2.248886e+14   43234              456728   
5  2446.60  2466.90  1211892  2.989615e+14   84503              714306   
6  2417.70  2433.96  1318166  3.208362e+14  101741              886368   
7  2443.80  2434.81   782704  1.905739e+14   47699              450768   
8  2512.30  2490.01  1598821  3.981082e+14   81743              865777   
9  2512.30  2490.01  1598821  3.981082e+14   81743              865777   

   %Deliverble  
0       0.2883  
1       0.6683  
2       0.6683  
3       0.6683  
4       0.5207  
5       0.5894  
6       0.6724  
7       0.5759  
8       0.5415  
9       0.5415

In [96]:
X_tcs = tcs_data.loc[:,'Prev Close':'%Deliverble']
X_tcs = X_tcs.drop('Open',axis =1)
X_tcs = X_tcs.values

In [107]:
X_tcs=X_tcs.astype('int')

In [108]:
Y_tcs = tcs_data['Open'].values
Y_tcs = Y_tcs.astype('int')
Y_tcs

array([2567, 2551, 2581, 2529, 2470, 2442, 2455, 2517, 2520, 2516, 2533,
       2543, 2536, 2520, 2522, 2516, 2514, 2512, 2503, 2538, 2560, 2482,
       2511, 2568, 2520, 2553, 2561, 2510, 2455, 2479, 2470, 2560, 2585,
       2636, 2698, 2671, 2694, 2710, 2679, 2659, 2677, 2679, 2682, 2788,
       2750, 2640, 2648, 2642, 2623, 2638, 2585, 2582, 2590, 2576, 2596,
       2616, 2630, 2591, 2553, 2531, 2525, 2569, 2558, 2558, 2562, 2594,
       2659, 2648, 2664, 2654, 2626, 2557, 2480, 2428, 2431, 2472, 2455,
       2499, 2510, 2484, 2480, 2491, 2501, 2515, 2464, 2560, 2535, 2560,
       2547, 2520, 2515, 2514, 2519, 2520, 2557, 2550, 2620, 2605, 2608,
       2603, 2617, 2609, 2616, 2604, 2617, 2592, 2590, 2585, 2566, 2605,
       2571, 2505, 2500, 2521, 2515, 2535, 2547, 2600, 2580, 2562, 2550,
       2572, 2585, 2563, 2600, 2573, 2580, 2632, 2597, 2595, 2559, 2475,
       2511, 2501, 2543, 2546, 2564, 2576, 2561, 2517, 2497, 2488, 2499,
       2511, 2516, 2489, 2503, 2510, 2520, 2565, 25

In [109]:
random.seed(1)

In [110]:
X_train,X_test,y_train,y_test = train_test_split(X_tcs,Y_tcs,test_size = 0.25,random_state = 0)

In [111]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\hp\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [112]:
import random
random.seed(1)
from sklearn.svm import SVC
classifier=SVC(kernel = 'rbf',random_state = 0)


In [113]:
classifier.fit(X_train,y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [114]:
y_pred = classifier.predict(X_test)


In [115]:
from sklearn.metrics import mean_squared_error
from math import sqrt
rms = sqrt(mean_squared_error(y_test, y_pred))
rms

39.42080668885405

### let use one more model

In [118]:
classifier = DecisionTreeRegressor(random_state = 42)
classifier.fit(X_train,y_train)


DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=42, splitter='best')

In [119]:
y_pred = classifier.predict(X_test)

In [120]:
from sklearn.metrics import mean_squared_error
from math import sqrt
rms = sqrt(mean_squared_error(y_test, y_pred))
rms

19.66124401275342

### Not bad.Decision tree always good !!

### same for infy

In [121]:
infy_data = pd.read_csv('infy_stock.csv')

In [124]:
infy_data['Date']=pd.to_datetime(infy_data['Date'])
infy_data.set_index('Date',inplace = True)

infy_data=infy_data.resample('D').ffill().reset_index()

In [125]:
infy_data.head(10)

Date Symbol Series  Prev Close     Open     High      Low     Last  \
0 2015-01-01   INFY     EQ     1972.55  1968.95  1982.00  1956.90  1971.00   
1 2015-01-02   INFY     EQ     1974.40  1972.00  2019.05  1972.00  2017.95   
2 2015-01-03   INFY     EQ     1974.40  1972.00  2019.05  1972.00  2017.95   
3 2015-01-04   INFY     EQ     1974.40  1972.00  2019.05  1972.00  2017.95   
4 2015-01-05   INFY     EQ     2013.20  2009.90  2030.00  1977.50  1996.00   
5 2015-01-06   INFY     EQ     1995.90  1980.00  1985.00  1934.10  1965.10   
6 2015-01-07   INFY     EQ     1954.20  1965.00  1974.75  1950.00  1966.05   
7 2015-01-08   INFY     EQ     1963.55  1985.60  1997.00  1950.00  1979.25   
8 2015-01-09   INFY     EQ     1973.45  1980.10  2109.00  1913.05  2075.30   
9 2015-01-10   INFY     EQ     1973.45  1980.10  2109.00  1913.05  2075.30   

     Close     VWAP    Volume      Turnover  Trades  Deliverable Volume  \
0  1974.40  1971.34    500691  9.870306e+13   14908              258080   
1  2013.20  2003.25   1694580  3.394669e+14   54166             1249104   
2  2013.20  2003.25   1694580  3.394669e+14   54166             1249104   
3  2013.20  2003.25   1694580  3.394669e+14   54166             1249104   
4  1995.90  2004.59   2484256  4.979911e+14   82694             1830962   
5  1954.20  1954.82   2416829  4.724458e+14  108209             1772070   
6  1963.55  1962.59   1812479  3.557162e+14   62463             1317720   
7  1973.45  1972.78   3391230  6.690160e+14   92752             2686012   
8  2074.45  2037.69  11215832  2.285439e+15  359214             3369489   
9  2074.45  2037.69  11215832  2.285439e+15  359214             3369489   

   %Deliverble  
0       0.5154  
1       0.7371  
2       0.7371  
3       0.7371  
4       0.7370  
5       0.7332  
6       0.7270  
7       0.7920  
8       0.3004  
9       0.3004

In [126]:
X_infy = infy_data.loc[:,'Prev Close':'%Deliverble']
X_infy = X_infy.drop('Open',axis =1)
X_infy = X_infy.values

In [127]:
X_infi=X_infy.astype('int')

In [129]:
Y_infy = infy_data['Open'].values
Y_infy = Y_infy.astype('int')
Y_infy

array([1968, 1972, 1972, 1972, 2009, 1980, 1965, 1985, 1980, 1980, 1980,
       2092, 2107, 2098, 2135, 2148, 2148, 2148, 2120, 2107, 2131, 2174,
       2200, 2200, 2200, 2200, 2221, 2150, 2145, 2161, 2161, 2161, 2141,
       2136, 2139, 2150, 2205, 2205, 2205, 2200, 2243, 2280, 2283, 2299,
       2299, 2299, 2280, 2280, 2290, 2294, 2328, 2328, 2328, 2300, 2279,
       2288, 2307, 2274, 2274, 2274, 2303, 2290, 2300, 2267, 2267, 2267,
       2267, 2259, 2198, 2194, 2179, 2225, 2225, 2225, 2210, 2266, 2254,
       2234, 2241, 2241, 2241, 2253, 2234, 2222, 2208, 2164, 2164, 2164,
       2205, 2245, 2198, 2198, 2198, 2198, 2198, 2179, 2175, 2182, 2211,
       2210, 2210, 2210, 2238, 2238, 2236, 2222, 2180, 2180, 2180, 2176,
       2148, 2151, 2148, 2135, 2135, 2135, 2000, 1982, 1960, 1960, 1960,
       1960, 1960, 1959, 2000, 1975, 1922, 1958, 1958, 1958, 1965, 1993,
       1951, 1960, 1935, 1935, 1935, 1970, 1987, 2040, 2048, 2044, 2044,
       2044, 2050, 2020, 2007, 1975, 2004, 2004, 20

In [130]:
X_train,X_test,y_train,y_test = train_test_split(X_infy,Y_infy,test_size = 0.25,random_state = 0)

In [131]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [132]:
import random
random.seed(1)
from sklearn.svm import SVC
classifier=SVC(kernel = 'rbf',random_state = 0)

In [133]:
classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [134]:
y_pred = classifier.predict(X_test)


In [135]:
from sklearn.metrics import mean_squared_error
from math import sqrt
rms = sqrt(mean_squared_error(y_test, y_pred))
rms

70.3466571623204

### lets use one more model

In [136]:
classifier = DecisionTreeRegressor(random_state = 42)
classifier.fit(X_train,y_train)


DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=42, splitter='best')

In [138]:
y_pred=classifier.predict(X_test)

In [139]:
from sklearn.metrics import mean_squared_error
from math import sqrt
rms = sqrt(mean_squared_error(y_test, y_pred))
rms

8.800938685113676

In [142]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)